const d3 = D3ArrayLib.default;
const out = [];
const log = (k, v) => out.push(k + " " + JSON.stringify(v));
const data = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3];
log("min", d3.min(data));
log("max", d3.max(data));
log("extent", d3.extent(data));
log("sum", d3.sum(data));
log("mean", d3.mean(data));
log("median", d3.median(data));
log("range10", d3.range(10));
log("range.step", d3.range(0, 10, 2));
log("ascending", data.slice().sort(d3.ascending));
log("descending", data.slice().sort(d3.descending));
log("bisect.left", d3.bisectLeft([1, 3, 5, 7, 9], 4));
log("bisect.right", d3.bisectRight([1, 3, 5, 7, 9], 5));
const grouped = d3.group([{ k: "a", v: 1 }, { k: "b", v: 2 }, { k: "a", v: 3 }], (d) => d.k);
log("group.size", grouped.size);
log("group.a", grouped.get("a"));
console.log(out.join("\n"));
