console.log(1 + 2);
console.log(10 - 3);
console.log(4 * 5);
console.log(10 / 3);
console.log(10 % 3);
console.log(2 ** 8);
console.log("hello" + " " + "world");
console.log("5" + 3);
console.log("5" - 3);
console.log(true + 1);
console.log(null + 1);
console.log(typeof 42);
console.log(typeof "hello");
console.log(typeof true);
console.log(typeof undefined);
console.log(typeof null);
console.log(typeof {});
console.log(typeof function(){});
console.log(!true);
console.log(!false);
console.log(!0);
console.log(!1);
console.log(!"");
console.log(!"hello");
