const EventEmitter = EventemitterLib.default;
const out = [];
const log = (k, v) => out.push(k + " " + JSON.stringify(v));
const ee = new EventEmitter();
const events = [];
ee.on("hello", (...args) => events.push(["hello"].concat(args)));
ee.on("data", (x) => events.push(["data", x]));
const once = (...args) => events.push(["once"].concat(args));
ee.once("startup", once);
ee.emit("hello", "world", 42);
ee.emit("data", { n: 1 });
ee.emit("data", { n: 2 });
ee.emit("startup", "boot");
ee.emit("startup", "boot2");
log("events", events);
log("listenerCount.data", ee.listenerCount("data"));
log("listenerCount.startup", ee.listenerCount("startup"));
ee.removeAllListeners("data");
log("after.remove.data", ee.listenerCount("data"));
log("eventNames", ee.eventNames().sort());
console.log(out.join("\n"));
