const ss = SsLib.default;
const out = [];
const log = (k, v) => out.push(k + " " + JSON.stringify(v));
const data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
log("mean", ss.mean(data));
log("median", ss.median(data));
log("mode", ss.mode([1, 1, 2, 2, 2, 3, 4]));
log("std", ss.standardDeviation(data).toFixed(6));
log("variance", ss.variance(data));
log("quantile.50", ss.quantile(data, 0.5));
log("quantile.90", ss.quantile(data, 0.9));
log("min", ss.min(data));
log("max", ss.max(data));
log("sum", ss.sum(data));
log("product", ss.product([1, 2, 3, 4]));
const corr = ss.sampleCorrelation([1, 2, 3, 4], [2, 4, 6, 8]);
log("correlation", corr);
const reg = ss.linearRegression([[1, 2], [2, 4], [3, 6], [4, 8]]);
log("linreg.m", reg.m);
log("linreg.b", reg.b);
console.log(out.join("\n"));
