<?php

declare(strict_types=1);

return [
    'test262_categories' => [
        'language/literals',
        'language/types',
        'language/expressions',
        'language/statements',
        'language/block-scope',
        'language/function-code',
        'language/arguments-object',
        'language/destructuring',
        'language/computed-property-names',
        'language/rest-parameters',
        'language/directive-prologue',
        'language/eval-code',
        'language/asi',
        'language/keywords',
        'language/white-space',
        'language/line-terminators',
        'language/comments',
        'language/future-reserved-words',
        'language/reserved-words',
        'language/identifier-resolution',
        'built-ins/Array',
        'built-ins/Boolean',
        'built-ins/Date',
        'built-ins/Error',
        'built-ins/Function',
        'built-ins/JSON',
        'built-ins/Map',
        'built-ins/Math',
        'built-ins/Number',
        'built-ins/Object',
        'built-ins/RegExp',
        'built-ins/Set',
        'built-ins/String',
        'built-ins/Symbol',
        'built-ins/parseInt',
        'built-ins/parseFloat',
        'built-ins/isNaN',
        'built-ins/isFinite',
        'annexB/built-ins/String',
        'annexB/built-ins/escape',
        'annexB/built-ins/unescape',
    ],
    'test262_skipped_features' => [
        // Threading (PHP is single-threaded)
        'Atomics',
        'Atomics.pause',
        'SharedArrayBuffer',
        // ES modules (in progress)
        'import-assertions',
        'import-attributes',
        'dynamic-import',
        'arbitrary-module-namespace-names',
        'json-modules',
        'source-phase-imports',
        // Massive API (in progress)
        'Temporal',
    ],
];
